### PR TITLE
Add OmniAuth v2 support

### LINKED ISSUE #62: Add OmniAuth 2 compatibility
Breaking changes:

- [x] omniauth/omniauth@ad6228c04ec7496777252496687b06317ae5b8cc

```
rspec ./spec/omniauth/strategies/cas_spec.rb[1:3:1:1:1] # OmniAuth::Strategies::CAS GET /auth/cas with a referer behaves like a CAS redirect response is expected to be redirect
rspec ./spec/omniauth/strategies/cas_spec.rb[1:3:1:1:2] # OmniAuth::Strategies::CAS GET /auth/cas with a referer behaves like a CAS redirect response redirects to the CAS server
rspec ./spec/omniauth/strategies/cas_spec.rb[1:3:2:1:1] # OmniAuth::Strategies::CAS GET /auth/cas with an explicit return URL behaves like a CAS redirect response is expected to be redirect
rspec ./spec/omniauth/strategies/cas_spec.rb[1:3:2:1:2] # OmniAuth::Strategies::CAS GET /auth/cas with an explicit return URL behaves like a CAS redirect response redirects to the CAS server
```

- [x] omniauth/omniauth@7f20a03d92298f59e2f570061498a1d188713f22

```
rspec ./spec/omniauth/strategies/cas_spec.rb[1:4:3:1:1:3:4:1] # OmniAuth::Strategies::CAS GET /auth/cas/callback with a valid ticket with JASIG flavored XML behaves like successful_validation request.env['omniauth.auth'] the info hash includes user info attributes
rspec ./spec/omniauth/strategies/cas_spec.rb[1:4:3:2:1:3:4:1] # OmniAuth::Strategies::CAS GET /auth/cas/callback with a valid ticket with classic XML behaves like successful_validation request.env['omniauth.auth'] the info hash includes user info attributes
```

- [x] Backward compatibility
- [x] Keep testing OmniAuth 1 with GET

### PR DESCRIPTION
**Pull request by tagliala**
Close #62

### CODE REVIEW

**Comment by tagliala** [comment]
I do not have access to rubygems, but yes, that is the intention

**Comment by dlindahl** [comment]
@tagliala what is your rubygems username/email?

**Comment by tagliala** [comment]
@dlindahl https://rubygems.org/profiles/tagliala

**Comment by tagliala** [comment]
@mjankowski v3.0.0.beta.1 released to rubygems

**Comment by tagliala** [comment]
Hello, is someone using the v3 beta? Can we release v3 ?

**Pull request merged**
