### PR TITLE
Relax version requirements; support Rails 5

### PR DESCRIPTION
**Pull request by lucaspiller**
Relaxes the dependency on Omniauth, to allow 1.3 to be installed which is required for Rails 5.

### CODE REVIEW

**Comment by dlindahl** [comment]
If you can fix the build error, I will blindly merge this in. Something to do with minimum required Ruby version in the `.travis.yml` file.

**Comment by vasilakisfil** [comment]
@lucaspiller bump

**Comment by lucaspiller** [comment]
Ok fixed, as there is no Gemfile.lock it was trying to install the newest version of Rack which requires Ruby 2.2.2+. Apparently Bundler isn't smart enough to figure that out? I've just changed the Gemfile to take into account that logic. For a gem I'm not sure whether a Gemfile.lock is a good idea - on one hand it prevents these issues, but on the other it also means that it won't test compatibility against the latest and greatest dependencies.

**Comment by lucaspiller** [comment]
Also @dlindahl I saw your comment on the other PR about not having access to a CAS server to test and maintain this project. At [IFAD](https://github.com/ifad/) we are big users of CAS, so we can probably take over. Ping @vjt!

**Comment by sahglie** [comment]
+1

**Comment by mpeteuil** [comment]
@lucaspiller The Gemfile.lock file is generally not checked in when the project in question is a gem. See Yehuda's post _[Clarifying the Roles of the .gemspec and Gemfile](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/)_ for more details.

If there's anything I can do to help get this in let me know.

Cheers

**Comment by dlindahl** [comment]
Few more changes:
* Drop support for all [unmaintained Ruby versions](https://www.ruby-lang.org/en/downloads/) from the Travis config
* Add support for 2.3.1 (Latest)
* Remove the conditional from the gemspec. If `rack` 2 is required, its easier to drop Ruby 2.1 support than deal with hidden dependencies

Do that and I'll merge this in and make you a contributor.

**Comment by lucaspiller** [comment]
I'd prefer not to drop support for Ruby < 2.2.2 as we still have a large number of applications running on Ruby 2.1, it's still a supported Ruby version until probably next year at least.

The original issue of the specs failing is actually a bug in Bundler, it doesn't check or respect the `required_ruby_version` option in the Gemfile:

* https://github.com/bundler/bundler/pull/4651#issuecomment-235415688
* https://github.com/bundler/bundler/issues/4819

I find it hard to believe this is the first Gem that has come across this issue - does anyone know how other projects have handled this?

**Comment by dlindahl** [comment]
Upgrade your apps then. 😜 

LGTM!

**Comment by vjt** [comment]
Hey @dlindahl,

if it were that easy to _just upgrade_ :-). Thanks for keeping Ruby 2.1 supported in the latest `omniauth-cas`, at least as long as it is supported upstream.

@lucaspiller, thanks for the ping, I will provide the project a test infrastructure for CAS authenticating against an OpenLDAP. Summer is coming, and with that lots of heat and free time to play with UNIX toys.

Cheers! 🍻

**Comment by dlindahl** [comment]
@lucaspiller ping me with your RubyGems email address so I can add you as an owner of the gem

**Comment by mpeteuil** [comment]
@lucaspiller @dlindahl Thoughts on a bumping the version with these changes? If so, following semver would that be a major version change with the support for some older rubies being dropped?

**Comment by dlindahl** [comment]
You are contributors, go for it! I just need some emails to add to RubyGems
so you can push the gem out. I'm out of service until Monday though

**Comment by lucaspiller** [comment]
@dlindahl Oops, sorry missed this! Here you go:

luca@stackednotion.com
vjt@openssl.it

I'll make a release once you've added us, as the current version doesn't include this change so won't work with Rails 5. Thanks!

**Comment by lucaspiller** [comment]
@mpeteuil This change only lifts a restriction in the gemspec, there are no actual code changes, so old versions of Ruby should still work.

**Comment by dlindahl** [comment]
@mpeteuil @lucaspiller @vjt: I've added you all as owners of this gem: https://rubygems.org/gems/omniauth-cas

**Comment by lucaspiller** [comment]
Thanks @dlindahl. Can you give us commit access to this repo, or we can fork it to our organisation if you want to step away.

**Comment by dlindahl** [comment]
To prevent URL breakage, I'd recommend keeping it here. @lucaspiller, you should have full repo access, but GH says you have not accepted the Collaborator's invite. Check your email. I can resend if you can't find it. Let me know!

**Comment by lucaspiller** [comment]
Ah I can't find it, must have deleted it accidentally :no_mouth:

**Comment by dlindahl** [comment]
Re-sent!

**Comment by lucaspiller** [comment]
Ok, I'm in. v1.1.1 is away! Pushed and tagged here, and new gem pushed to RubyGems. 🎆  🎉 💃

**Pull request merged**
