### PR TITLE
Move CI build to GitHub Actions

### PR DESCRIPTION
**Pull request by tagliala**

### CODE REVIEW

**Comment by tagliala** [comment]
@vjt I don't know why it is not running the workflow here, here it is the result of the CI build on my fork: https://github.com/tagliala/omniauth-cas/pull/1/checks

maybe try to force push here as yourself, I don't know if it is a permission issue

**Comment by tagliala** [comment]
@vjt any chance to run GitHub actions on this PR?

**Comment by tagliala** [comment]
Hi @dlindahl, any chance to allow GitHub actions on this PR?

**Review by dlindahl — APPROVED** [review]
LGTM 🎉

**Pull request merged**
